import { persistStore } from "redux-persist";
import { PersistGate } from "redux-persist/integration/react";
import Nav from "../components/nav";
import { ReduxProvider } from "../store/provider";
import { store } from "../store/store";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
